### ISSUE TITLE
trying to wield an unid:d vampiric weapon can cause script to halt

### ISSUE THREAD

**Issue by kribjo** [elliptic/qw#1]
Script version: 2015-02-16 up to and including commit 8d50f17
Crawl version: 0.16-a0-4017-g5508f4c (console)

Current behaviour:
qw tried to wield an unid:d weapon, the weapon turned out to be vampiric and since qw's nutrition level was not high enough the weapon could not be wielded, the script halted with the line "Wield_weapon failed despite returning true".

Expected behaviour:
qw should understand that the weapon was now id:d as vampiric and not wielded, this should be an expected case and not cause a script halt.

log output:
    14 | D:1      | 14 ||| Wielding weapon runed hand axe.

^P output:
e - a runed hand axe
14 ||| Wielding weapon runed hand axe.
This weapon is vampiric, and you must be Full or above to equip it.
e - a vampiric hand axe
Wield_weapon failed despite returning true.

Crawl version 0.16-a0-4017-g5508f4c
Save file version 34.134
Compiled with GCC 4.9.2 on Feb 16 2015 at 07:40:49
Build platform: x86_64-linux-gnu
Platform: i686-w64-mingw32.static
CFLAGS: -O2 -pipe -DWINMM_PLAY_SOUNDS -D__USE_MINGW_ANSI_STDIO -DUSE_SOUND -Wall -Wformat-security -Wundef -Wno-array-bounds -Wno-format-zero-length -Wmissing-declarations -Wredundant-decls -Wno-parentheses -Wwrite-strings -Wshadow -pedantic -Wuninitialized -Iutil -I. -Irltiles -isystem contrib/install/i686-w64-mingw32.static/include -DWIZARD -DASSERTS -DREGEX_PCRE -DCLUA_BINDINGS
LDFLAGS: -O2

/TAS 2012

**Comment by elliptic** [comment]
Fixed now, thanks!
