### ISSUE TITLE
lemuel_draconian_sentries vault is unpassable

### ISSUE THREAD

**Issue by Pipeliner** [elliptic/qw#3]
because we don't use wands of dig or disintegration and can't reach those summoners
see  http://dobrazupa.org/morgue/tstbtto/morgue-tstbtto-20150215-224007.txt for example
with all cages manually open bot killed all draconians but there were no resources left to survive Zot:5

**Comment by elliptic** [comment]
Yeah, the 2-3 vaults like this in Zot are pretty annoying. Currently my plan is to have qw search for and pick up/identify a wand of digging/disintegration before entering Zot and then try to recognize those vaults, but doing all that will be a fair amount of work.
